# FROM elestio/pgadmin:latest

# # タイムゾーン
# ENV TZ Asia/Tokyo

# # 日本語化
# # RUN localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8
# ENV LANG ja_JP.UTF-8


FROM dpage/pgadmin4:7.8

ENV TZ=Asia/Tokyo
ENV LANG=ja_JP.UTF-8