
services:
  python:
    build: python
    container_name: python_app_container
    ports:
      - "8000:9540"
      - "8001:9541"
      - "8002:9542"
      - "5001:5001"  # デバッガ用ポート
    volumes:
      - ./work:/work
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /work
    env_file:
      - .env  # ← ここで .env ファイルを指定    
    command: ["python", "app.py"]