version: "3.8"

services:
  python:
    build: python
    container_name: python_app_container
    ports:
      - "9540:9540"
      - "9541:9541"
      - "9542:9542"
      - "5001:5001"  # デバッガ用ポート
    volumes:
      - ./work:/work
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /work
    env_file:
      - .env  # ← ここで .env ファイルを指定    
    environment:
      - PYTHONUNBUFFERED=1    
    command: ["python", "app.py"]